apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: equipo4-chatbot
  template:
    metadata:
      labels:
        app: equipo4-chatbot
    spec:
      containers:
      - name: equipo4-chatbot
        image: ${DOCKER_REGISTRY}/chatbot4-springboot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: oracle-wallet-volume
          mountPath: /wallet
          readOnly: true
      volumes:
      - name: oracle-wallet-volume
        secret:
          secretName: oracle-wallet-secret
  restartPolicy: Always